# Generated by Django 4.2.13 on 2024-06-17 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("wagtailcore", "0090_formsubmission"),
    ]

    operations = [
        migrations.CreateModel(
            name="ColophonSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "site_honcho",
                    models.CharField(
                        default="Dan Crichton",
                        help_text="JPL cognizant person who manages the site",
                    ),
                ),
                (
                    "webmaster",
                    models.CharField(
                        default="Rojeh Yaghoobi",
                        help_text="JPL cognizant person who masters the site",
                    ),
                ),
                (
                    "clearance",
                    models.CharField(
                        default="CL № 22-6220", help_text="JPL clearance number"
                    ),
                ),
                (
                    "site",
                    models.OneToOneField(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wagtailcore.site",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
