# Generated by Django 4.2.13 on 2024-06-14 19:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jpledrnbiokeytheme", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="colophonsettings",
            name="site_editor",
        ),
        migrations.AddField(
            model_name="colophonsettings",
            name="site_manager",
            field=models.CharField(
                default="Dan Crichton",
                help_text="JPL cognizant person who manages the site",
            ),
        ),
        migrations.AlterField(
            model_name="colophonsettings",
            name="clearance",
            field=models.CharField(
                default="CL № 22-6220", help_text="JPL clearance number"
            ),
        ),
        migrations.AlterField(
            model_name="colophonsettings",
            name="webmaster",
            field=models.CharField(
                default="Rojeh Yaghoobi",
                help_text="JPL cognizant person who masters the site",
            ),
        ),
    ]
