# Generated by Django 4.2.13 on 2024-06-17 18:56

from django.db import migrations, models
import django.db.models.deletion
import jpl.edrn.biokey.streams.blocks
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("wagtailcore", "0090_formsubmission"),
    ]

    operations = [
        migrations.CreateModel(
            name="FlexPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "body",
                    wagtail.fields.StreamField(
                        [
                            (
                                "title",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            "text",
                                            wagtail.blocks.CharBlock(
                                                help_text="Title to display",
                                                max_length=100,
                                                required=True,
                                            ),
                                        )
                                    ]
                                ),
                            ),
                            (
                                "rich_text",
                                wagtail.blocks.RichTextBlock(
                                    help_text="Richly formatted text",
                                    icon="doc-full",
                                    label="Rich Text",
                                ),
                            ),
                            (
                                "block_quote",
                                jpl.edrn.biokey.streams.blocks.BlockQuoteBlock(
                                    help_text="Block quote"
                                ),
                            ),
                            (
                                "raw_html",
                                wagtail.blocks.RawHTMLBlock(
                                    help_text="Raw HTML (use with care)"
                                ),
                            ),
                        ],
                        blank=True,
                        null=True,
                        use_json_field=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "web page",
                "verbose_name_plural": "web pages",
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="HomePage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "body",
                    wagtail.fields.StreamField(
                        [
                            (
                                "title",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            "text",
                                            wagtail.blocks.CharBlock(
                                                help_text="Title to display",
                                                max_length=100,
                                                required=True,
                                            ),
                                        )
                                    ]
                                ),
                            ),
                            (
                                "rich_text",
                                wagtail.blocks.RichTextBlock(
                                    help_text="Richly formatted text",
                                    icon="doc-full",
                                    label="Rich Text",
                                ),
                            ),
                            (
                                "block_quote",
                                jpl.edrn.biokey.streams.blocks.BlockQuoteBlock(
                                    help_text="Block quote"
                                ),
                            ),
                            (
                                "raw_html",
                                wagtail.blocks.RawHTMLBlock(
                                    help_text="Raw HTML (use with care)"
                                ),
                            ),
                        ],
                        blank=True,
                        null=True,
                        use_json_field=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "home page",
                "verbose_name_plural": "home pages",
            },
            bases=("wagtailcore.page",),
        ),
    ]
