# Generated by Django 4.2.11 on 2024-04-25 18:52

from django.db import migrations
import jpl.edrn.biokey.streams.blocks
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):
    dependencies = [
        ("jpledrnbiokeycontent", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flexpage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    (
                        "title",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "text",
                                    wagtail.blocks.CharBlock(
                                        help_text="Title to display",
                                        max_length=100,
                                        required=True,
                                    ),
                                )
                            ]
                        ),
                    ),
                    (
                        "rich_text",
                        wagtail.blocks.RichTextBlock(
                            help_text="Richly formatted text",
                            icon="doc-full",
                            label="Rich Text",
                        ),
                    ),
                    (
                        "block_quote",
                        jpl.edrn.biokey.streams.blocks.BlockQuoteBlock(
                            help_text="Block quote"
                        ),
                    ),
                ],
                blank=True,
                null=True,
                use_json_field=True,
            ),
        ),
    ]
