# Generated by Django 4.2.11 on 2024-04-25 19:21

from django.db import migrations, models
import django.db.models.deletion
import jpl.edrn.biokey.streams.blocks
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):
    dependencies = [
        ("wagtailimages", "0025_alter_image_file_alter_rendition_file"),
        ("jpledrnbiokeycontent", "0002_alter_flexpage_body"),
    ]

    operations = [
        migrations.AddField(
            model_name="flexpage",
            name="search_image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
                verbose_name="Search image",
            ),
        ),
        migrations.AlterField(
            model_name="flexpage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    (
                        "title",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "text",
                                    wagtail.blocks.CharBlock(
                                        help_text="Title to display",
                                        max_length=100,
                                        required=True,
                                    ),
                                )
                            ]
                        ),
                    ),
                    (
                        "rich_text",
                        wagtail.blocks.RichTextBlock(
                            help_text="Richly formatted text",
                            icon="doc-full",
                            label="Rich Text",
                        ),
                    ),
                    (
                        "block_quote",
                        jpl.edrn.biokey.streams.blocks.BlockQuoteBlock(
                            help_text="Block quote"
                        ),
                    ),
                    (
                        "raw_html",
                        wagtail.blocks.RawHTMLBlock(
                            help_text="Raw HTML (use with care)"
                        ),
                    ),
                ],
                blank=True,
                null=True,
                use_json_field=True,
            ),
        ),
    ]
