# Generated by Django 4.2.11 on 2024-05-03 19:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jpledrnbiokeyusermgmt", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="datainformationtree",
            name="manager_dn",
            field=models.CharField(
                default="uid=admin,ou=system",
                help_text="DN of the manager of the server",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="datainformationtree",
            name="manager_password",
            field=models.CharField(
                default="password", help_text="Password of manager DN", max_length=80
            ),
        ),
        migrations.AlterField(
            model_name="datainformationtree",
            name="uri",
            field=models.CharField(
                help_text='URI to the LDAP server as an "ldap:" or "ldaps: URL',
                max_length=200,
                validators=[
                    django.core.validators.URLValidator(schemes=["ldap", "ldaps"])
                ],
            ),
        ),
    ]
