# Generated by Django 4.2.11 on 2024-05-29 16:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "jpledrnbiokeyusermgmt",
            "0003_rename_datainformationtree_directoryinformationtree",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="directoryinformationtree",
            name="user_base",
            field=models.CharField(
                default="ou=users,o=organization",
                help_text="Base DN where to find users",
                max_length=600,
            ),
        ),
    ]
