# Generated by Django 4.2.13 on 2024-06-21 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("jpledrnbiokeyusermgmt", "0003_alter_emailsettings_new_users_addresses"),
    ]

    operations = [
        migrations.AddField(
            model_name="directoryinformationtree",
            name="creation_notification_template",
            field=models.TextField(
                default="Notice:\n\n{fn} {ln} has registered for a {consortium} account with the user ID {uid}.\n\nThis account is pending approval. Please visit {url} as an administrator to approve or reject the account. Not sure how to log in as an administrator? There's a login link in the footer at the bottom of the page.\n\nIf you need to reach out to this user first, they provided the following details:\n\nPhone: {phone}\nEmail: {email}\n\nThanks,\n—BioKey\n",
                help_text="Email template for administrators when notified of a newly-created account",
            ),
        ),
        migrations.CreateModel(
            name="PendingUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uid", models.CharField(max_length=15)),
                ("fn", models.CharField(max_length=128)),
                ("ln", models.CharField(max_length=128)),
                ("phone", models.CharField(max_length=40)),
                ("email", models.EmailField(max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "page",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pending_users",
                        to="jpledrnbiokeyusermgmt.directoryinformationtree",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
                "indexes": [
                    models.Index(
                        fields=["created_at"], name="jpledrnbiok_created_6a79f0_idx"
                    )
                ],
            },
        ),
    ]
