# Generated by Django 4.2.13 on 2024-06-21 18:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "jpledrnbiokeyusermgmt",
            "0004_directoryinformationtree_creation_notification_template_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="directoryinformationtree",
            name="approval_template",
            field=models.TextField(
                default="Greetings {fn} {ln}:\n\nWe're writing to let you know that your account, {uid}, has been approved and you can now use {consortium} applications with expanded access.\n\nAs a reminder, if you need to change your password or if you've forgotten it, simply visit this URL: {url}\n\nThank you.\n",
                help_text="Email template for end-users letting them now their accounts have been approved.",
            ),
        ),
        migrations.AddField(
            model_name="directoryinformationtree",
            name="rejection_template",
            field=models.TextField(
                default="Greetings {fn} {ln}:\n\nWe're writing to inform you that your account, {uid}, was rejected for {consortium} and has been deleted.\n\nWe're sorry for the inconvenience.\n",
                help_text="Email template for end-users letting them now their accounts have been rejected.",
            ),
        ),
    ]
