# Generated by Django 4.2.11 on 2024-05-29 16:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jpledrnbiokeyusermgmt", "0005_directoryinformationtree_user_scope"),
    ]

    operations = [
        migrations.AlterField(
            model_name="directoryinformationtree",
            name="user_scope",
            field=models.IntegerField(
                choices=[(0, "base"), (1, "one-level"), (2, "subtree")],
                default=1,
                help_text="Search scope for users",
            ),
        ),
    ]
