# Generated by Django 4.2.11 on 2024-05-29 16:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jpledrnbiokeyusermgmt", "0006_alter_directoryinformationtree_user_scope"),
    ]

    operations = [
        migrations.AddField(
            model_name="directoryinformationtree",
            name="group_base",
            field=models.CharField(
                default="ou=groups,o=organization",
                help_text="Base DN where to find groups",
                max_length=600,
            ),
        ),
        migrations.AddField(
            model_name="directoryinformationtree",
            name="group_scope",
            field=models.IntegerField(
                choices=[(0, "base"), (1, "one-level"), (2, "subtree")],
                default=1,
                help_text="Search scope for groups",
            ),
        ),
    ]
