# Generated by Django 4.2.13 on 2024-06-25 22:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jpledrnbiokeyusermgmt", "0006_directoryinformationtree_acceptance_group"),
    ]

    operations = [
        migrations.AlterField(
            model_name="directoryinformationtree",
            name="approval_template",
            field=models.TextField(
                default="Greetings {fn} {ln}:\n\nWe're writing to let you know that your account, \"{uid}\", has been approved and you can now use {consortium} applications with expanded access.\n\nAs a reminder, if you need to change your password or if you've forgotten it, simply visit this URL: {url}\n\nThank you.\n",
                help_text="Email template for end-users letting them now their accounts have been approved.",
            ),
        ),
        migrations.AlterField(
            model_name="directoryinformationtree",
            name="creation_email_template",
            field=models.TextField(
                default='Hello!\n\nYour account, "{uid}", has been created for the {consortium}. Two things to be aware of:\n\n1. Your account is in the "pending" state. An administrator will review the account and may approve or reject it. Until it\'s approved, you won\'t have access to data or resources.\n\n2. While you\'re waiting, you can go ahead and set the password for this account. To do so, you\'ll need to visit the following link within {natural_delta}:\n\n{link}\n\nThis link will expire on {expiration_time} (UTC). If you can\'t visit the link in that time, visit {url} and choose the "Forgotten password" option for a fresh link.\n\nThank you.\n',
                help_text="Email template for end users' newly-created accounts",
            ),
        ),
        migrations.AlterField(
            model_name="directoryinformationtree",
            name="creation_notification_template",
            field=models.TextField(
                default='Notice:\n\n{fn} {ln} has registered for a "{consortium}"" account with the user ID "{uid}".\n\nThis account is pending approval. Please visit {url} as an administrator to approve or reject the account. Not sure how to log in as an administrator? There\'s a login link in the footer at the bottom of the page.\n\nIf you need to reach out to this user first, they provided the following details:\n\nPhone: {phone}\nEmail: {email}\n\nThanks,\n—BioKey\n',
                help_text="Email template for administrators when notified of a newly-created account",
            ),
        ),
        migrations.AlterField(
            model_name="directoryinformationtree",
            name="rejection_template",
            field=models.TextField(
                default='Greetings {fn} {ln}:\n\nWe\'re writing to inform you that your account, "{uid}", was rejected for {consortium} and has been deleted.\n\nWe regret any inconvenience.\n',
                help_text="Email template for end-users letting them now their accounts have been rejected.",
            ),
        ),
    ]
