# Generated by Django 4.2.11 on 2024-05-29 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("jpledrnbiokeyusermgmt", "0007_directoryinformationtree_group_base_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="EDRNDirectoryInformationTree",
            fields=[
                (
                    "directoryinformationtree_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="jpledrnbiokeyusermgmt.directoryinformationtree",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("jpledrnbiokeyusermgmt.directoryinformationtree",),
        ),
    ]
