# Generated by Django 4.2.11 on 2024-05-30 20:45

from django.db import migrations, models
import django.db.models.deletion
import wagtail.fields


class Migration(migrations.Migration):
    dependencies = [
        ("wagtailcore", "0089_log_entry_data_json_null_to_object"),
        ("jpledrnbiokeyusermgmt", "0008_edrndirectoryinformationtree"),
    ]

    operations = [
        migrations.CreateModel(
            name="NameRequestFormPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "intro",
                    wagtail.fields.RichTextField(
                        blank=True,
                        help_text="Introductory text to appear above the form",
                    ),
                ),
                (
                    "outro",
                    wagtail.fields.RichTextField(
                        blank=True, help_text="Text to appear below the form"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
    ]
