# Generated by Django 4.2.13 on 2024-06-04 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("wagtailcore", "0089_log_entry_data_json_null_to_object"),
        ("jpledrnbiokeyusermgmt", "0012_emailsettings_new_users_addresses"),
    ]

    operations = [
        migrations.CreateModel(
            name="PasswordSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reset_window",
                    models.IntegerField(
                        default=4320,
                        help_text="Number of minutes a user has to reset their password after sending the password reset email",
                    ),
                ),
                (
                    "site",
                    models.OneToOneField(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wagtailcore.site",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
