# Generated by Django 4.2.13 on 2024-06-07 22:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jpledrnbiokeyusermgmt", "0013_passwordsettings"),
    ]

    operations = [
        migrations.AddField(
            model_name="directoryinformationtree",
            name="creation_email_template",
            field=models.TextField(
                blank=True,
                default='Your account, "{uid}", has been created for the {consortium}. To set the password for this account, you\'ll need to visit the following link within {natural_delta}:\n\n{link}\n\nPlease note that this link will expire on {expiration_time} (UTC). If you can\'t visit the link in that time, visit {url} and choose the "Forgotten password" option for a fresh link.\n\nThank you.\n',
                help_text="Email template for end users' newly-created accounts",
            ),
        ),
        migrations.AddField(
            model_name="directoryinformationtree",
            name="reset_request_email_template",
            field=models.TextField(
                blank=True,
                default="To reset the password for account \"{uid}\", you'll need to visit the following link within {natural_delta}:\n\n{link}\n\nPlease note that link will expire on {expiration_time} (UTC). If you can't visit the link in that time, simply return to {url} and restart the forgotten password process.\n\nThank you.\n",
                help_text="Email template for end users' requests to reset their passwords",
            ),
        ),
        migrations.AddField(
            model_name="edrndirectoryinformationtree",
            name="dmcc_managed_email_template",
            field=models.TextField(
                blank=True,
                default='Your account, "{uid}" is managed the Data Management and Coordinating Center (DMCC) of the Early Detection Research Network.\n\nTo reset the password on this account, please visit the DMCC website at this address:\n\nhttps://www.compass.fhcrc.org/edrns/pub/user/resetPwd.aspx?t=pwd&amp;t2=pwd2&amp;sub=form&amp;w=1&amp;p=3&amp;param=reset&amp;t3=pwd&amp;sub2=lift\n\nThank you.\n',
                help_text="Email template to notify that theirs is a secure-site account",
            ),
        ),
    ]
