# Generated by Django 4.2.13 on 2024-06-09 18:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "jpledrnbiokeyusermgmt",
            "0014_directoryinformationtree_creation_email_template_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="directoryinformationtree",
            name="help_address",
            field=models.EmailField(
                default="help@email.address",
                help_text="Email address if users need help",
                max_length=50,
            ),
        ),
    ]
