# Generated by Django 4.2.13 on 2024-06-09 19:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jpledrnbiokeyusermgmt", "0015_directoryinformationtree_help_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="directoryinformationtree",
            name="forgotten_uid_template",
            field=models.TextField(
                default="Hello!\n\nSomeone, perhaps you, asked for the username for the {consortium} account that goes with this email address.\n\nThe username is: {uid}\n\nYou can visit {url} to change the password (if you know it), or reset the password (if forgotten).\n\nNote that if you did not request this, then simply ignore this email.\n\nThank you.\n",
                help_text="Email template for end users' to recover forgotten usernames, not forgotten passwords",
            ),
        ),
        migrations.AlterField(
            model_name="directoryinformationtree",
            name="creation_email_template",
            field=models.TextField(
                default='Hello!\n\nYour account, "{uid}", has been created for the {consortium}. To set the password for this account, you\'ll need to visit the following link within {natural_delta}:\n\n{link}\n\nPlease note that this link will expire on {expiration_time} (UTC). If you can\'t visit the link in that time, visit {url} and choose the "Forgotten password" option for a fresh link.\n\nThank you.\n',
                help_text="Email template for end users' newly-created accounts",
            ),
        ),
        migrations.AlterField(
            model_name="directoryinformationtree",
            name="reset_request_email_template",
            field=models.TextField(
                default='Hello!\n\nSomeone, perhaps you, requested a reset of the password for the account "{uid}".\n\nTo reset the password for account "{uid}", you\'ll need to visit the following link within {natural_delta}:\n\n{link}\n\nPlease note that link will expire on {expiration_time} (UTC). If you can\'t visit the link in that time, simply return to {url} and restart the forgotten password process.\n\nNote that if you did not request to reset the password, then simply ignore this email.\n\nThank you.\n',
                help_text="Email template for end users' requests to reset their passwords",
            ),
        ),
    ]
