# Generated by Django 4.2.13 on 2024-06-10 15:01

from django.db import migrations, models
import django.db.models.deletion
import wagtail.fields


class Migration(migrations.Migration):
    dependencies = [
        ("wagtailcore", "0089_log_entry_data_json_null_to_object"),
        (
            "jpledrnbiokeyusermgmt",
            "0016_directoryinformationtree_forgotten_uid_template_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="PasswordChangeFormPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "intro",
                    wagtail.fields.RichTextField(
                        blank=True,
                        help_text="Introductory text to appear above the form",
                    ),
                ),
                (
                    "outro",
                    wagtail.fields.RichTextField(
                        blank=True, help_text="Text to appear below the form"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
        migrations.AlterField(
            model_name="directoryinformationtree",
            name="forgotten_uid_template",
            field=models.TextField(
                default='Hello!\n\nSomeone, perhaps you, asked for the username for the {consortium} account that goes with this email address.\n\nThe username is: {uid}\n\nYou can visit {url} to change the password for "{uid}" (if you know it), or reset the password (if forgotten).\n\nNote that if you did not request this, then simply ignore this email.\n\nThank you.\n',
                help_text="Email template for end users' to recover forgotten usernames, not forgotten passwords",
            ),
        ),
    ]
