# Generated by Django 4.2.13 on 2024-06-12 21:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jpledrnbiokeyusermgmt", "0017_passwordchangeformpage_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="edrndirectoryinformationtree",
            name="dmcc_managed_email_template",
            field=models.TextField(
                blank=True,
                default='Your account, "{uid}", is managed the Data Management and Coordinating Center (DMCC) of the Early Detection Research Network.\n\nTo reset the password on this account, please visit the DMCC website at this address:\n\nhttps://www.compass.fhcrc.org/edrns/pub/user/resetPwd.aspx?t=pwd&amp;t2=pwd2&amp;sub=form&amp;w=1&amp;p=3&amp;param=reset&amp;t3=pwd&amp;sub2=lift\n\nThank you.\n',
                help_text="Email template to notify that theirs is a secure-site account",
            ),
        ),
    ]
