# Generated by Django 4.2.13 on 2024-06-13 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("wagtailimages", "0025_alter_image_file_alter_rendition_file"),
        (
            "jpledrnbiokeyusermgmt",
            "0018_alter_edrndirectoryinformationtree_dmcc_managed_email_template",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="directoryinformationtree",
            name="logo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="dit_logo",
                to="wagtailimages.image",
            ),
        ),
    ]
