# Generated by Django 4.2.13 on 2024-06-14 13:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jpledrnbiokeyusermgmt", "0019_directoryinformationtree_logo"),
    ]

    operations = [
        migrations.AddField(
            model_name="directoryinformationtree",
            name="page_title",
            field=models.CharField(
                default="Page title",
                help_text="Title to put at the top of the page",
                max_length=255,
            ),
        ),
    ]
